PHP 8 & Symfony 6
csrdelft/csrdelft.nl pull request #1153
Opened 2023-10-28 13:22 UTC by qurben

Zodra de stek naar PHP 8 kan natuurlijk

2023-10-28 13:25 UTC, qurben commented
Ci is nog niet blij :(

2024-10-26 13:15 UTC, NathanHuisman commented on phpunit.xml.dist
> -  <coverage processUncoveredFiles="true">
Coverage is wel handig om te hebben, we moeten maar even kijken hoe we dat het best kunnen configureren

2024-10-26 13:15 UTC, NathanHuisman commented on tests/bootstrap.php
> +if ($_SERVER['APP_DEBUG']) {
Waar is dit voor nodig?

2024-10-26 13:15 UTC, NathanHuisman commented on tests/lib/BrowserTestCase.php
> -		$status = $this->getStatus();
Panther kan als het goed is zelf screenshots maken, moet nog even kijken hoe we dat moeten configureren

2024-11-01 13:35 UTC, NathanHuisman requested changes

2024-11-01 13:35 UTC, NathanHuisman commented on .env.test
> +PANTHER_ERROR_SCREENSHOT_DIR='./var/error-screenshots'
Waarom werkt dit niet...

2025-02-06 13:22 UTC, NathanHuisman commented on .env.test
> +PANTHER_ERROR_SCREENSHOT_DIR='./var/error-screenshots'
Opgelost, probleem was dat de tearDown method overrided was door onze BrowserTestCase, terwijl Panther hem ook override. Dus we callen nu ook de parent tearDown

2025-02-08 16:18 UTC, NathanHuisman commented on composer.json
Doen we later

2025-02-08 16:20 UTC, NathanHuisman commented on config/services.yaml
> +  security.authorization_checker:
We gebruiken nu Symfony ipv Sensio auth logica, vandaar.

2025-02-08 16:21 UTC, NathanHuisman approved these changes
Alles is clear voor de upgrade

2025-02-08 16:22 UTC, merged