Update mail.html.twig
csrdelft/csrdelft.nl pull request #748
Opened 2020-09-07 10:22 UTC by Dyxl3ct1c

Design uitgewerkt, maar geen idee of the loopjes met dit ontwerp goed werken.

2020-09-07 10:50 UTC, qurben requested changes
Nice!

Nog een paar verbeterpuntjes, zo ziet ie er nu uit (met elif vervangen door elseif)
![](https://i.imgur.com/A8SiOoK.png)

Ik zou misschien ook in de wrapper één tabel stoppen en dan de tr's een background-color geven.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                    {% elif loop.index % 4 == 1 %}
elif is elseif in twig

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                    {% elif loop.index % 4 == 2 %}
Deze ook

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                          <div class="{{slashdirection}}">
slashdirection bestaat niet

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                      <td class="medium-donkerLiBo">
medium-donkerLiBo bestaat niet

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                          {{ bericht.titel | bbcode("mail") }}
Dit moet `bericht.bericht` zijn, in een vorige versie was dit per ongeluk titel.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="background-color: {{bgcolor}}">
Table mist tr

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +        table[class=body] h1 {
`table.body` ipv `table[class=body]` schaalt beter, dan gaat het niet stuk als dit element nog een klasse er bij krijgt.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +      .slashLiBo {
Zou misschien deze klassenamen uitschrijven, dan is het duidelijker wat er gaande is.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +    </table>
Deze `</table>` hoort nergens bij

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                        <h3><u><a id="{{ bericht.id }}"></a>{{ bericht.titel | bbcode("mail") }}</u></h3>
`<em>` ipv `<u>`, of miss geen underline als er geen link is. Je kan sowieso ieder element een id geven en er met `#id` naar verwijzen, hoeft geen `<a>` tag te zijn.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +      <tr>
tr zonder table

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                      <img src="https://www.csrdelft.nl/plaetjes/banners/Projectkwadraat.jpg">
Plaetje mist alt.

2020-09-07 10:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                  <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="background: #11273a">
ARIA role presentation is hier niet op z'n plek, er staan zinnige dingen in deze table.

Ik zou me ook niet te druk maken over het toevoegen van aria roles.

2020-09-28 15:50 UTC, qurben commented on templates/courant/mail.html.twig
> +                    {% else %}
Kan je deze `else` niet net zo goed buiten de loop hangen? Scheelt een conditional.

2020-09-28 15:51 UTC, qurben commented on templates/courant/mail.html.twig
> +                    {% else %}
En slikt dit niet het laatste bericht op?

2020-09-28 15:53 UTC, qurben commented on templates/courant/mail.html.twig
> +          background-image: -webkit-linear-gradient(95deg, #11273a 50%, #e8e8e8 50%);
Ik zou de `-webkit-` prefix hier droppen, bijna niemand gebruikt nog een browser die de normale variant niet ondersteund.

2020-09-28 15:55 UTC, qurben commented on templates/courant/mail.html.twig
> +    <title>C.S.R.-courant</title>
Beter ook weer de date er bij, dat is nice voor het archief.

2020-09-28 16:02 UTC, qurben commented on templates/courant/mail.html.twig
> +        font-family: Open Sans;
Wil je alleen de titels in Open Sans? Als je toch webfonts aan het laden bent kun je misschien de rest ook in een fancy font stoppen.

2020-09-28 16:02 UTC, qurben commented on templates/courant/mail.html.twig
> +        font-family: Open Sans;
Hier ook een generic font-family bij, we willen geen Times New Roman als er iets niet ondersteund wordt.

2021-01-19 14:13 UTC, qurben requested changes
Deze versie ziet er heel nice uit!

Nog een plaar kleine commentaar puntjes.

2021-01-19 14:13 UTC, qurben commented on templates/courant/mail.html.twig
> +        max-width: 580px;
Ik zou misschien geen maximale breedte instellen. Als je het weg haalt ziet het er nog steeds goed uit en ik vind m zelf wel een beetje smal zo, niet wat ik gewend ben als ik normaal een mail ontvang.

2021-01-19 14:13 UTC, qurben commented on templates/courant/mail.html.twig
> +                              <img style='position: relative; width: 100%; border-radius: 5px' src="Projectkwadraat.jpg">
Sponsor hoeft er niet in, die wordt met een knopje ingeladen

2021-01-19 14:13 UTC, qurben commented on templates/courant/mail.html.twig
> +                      {% set bgcolor = '#4e698b' %}
Deze bgcolor is een beetje aan de lichte kant: https://contrastchecker.com/?c=ffffff&b=4e698b

2021-01-19 14:13 UTC, qurben commented on templates/courant/mail.html.twig
> +                        <img class="" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/C.S.R._Delft_Logo.svg/190px-C.S.R._Delft_Logo.svg.png" style="width:100px;" />
Je kan hier `https://csrdelft.nl/plaetjes/courant/beeldmerk.png` van maken, dat is hetzelfde plaatje.

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +                          <h4><u>{{ catName }}</u></h4>
`<u>` tag wordt hier wel een beetje misbruikt, zou gewoon de u styles op h* stoppen.

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +														<h3><u><a id="{{ bericht.id }}"></a>{{ bericht.titel | bbcode("mail") }}</u></h3>
Zelfde als andere u tag

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +        .ExternalClass {
.ExternalClass styles worden nergens gebruikt

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +        #MessageViewBody a {
Deze styles worden ook niet gebruikt

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +      #id {
Wordt niet gebruikt

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +        table[class=body] p,
Al deze `table[class=body]` styles worden niet gebruikt.

2021-01-30 15:48 UTC, qurben commented on templates/courant/mail.html.twig
> +        .apple-link a {
Ongebruikt

2021-01-30 15:51 UTC, qurben commented
Ik bedoelde met geen max-width zetten uberhaupt geen width zetten. Als je graag een specifieke breedte wil hebben zou ik alsnog max-width gebruiken, want nu wordt ie niet smaller als het scherm te smal is.

2021-02-07 22:08 UTC, Dyxl3ct1c commented
[https://i.imgur.com/ikV6MZf.png](url)

2021-02-07 22:10 UTC, Dyxl3ct1c commented
Gebruikte foto: https://csrdelft.nl/fotoalbum/2018-2019/18-07-30%20-%2018-08-06%20Voorbarverbouwing%20/_resized/66.jpg

2021-02-08 08:14 UTC, qurben commented
Ziet er cool uit met die foto

2021-02-08 08:18 UTC, qurben commented
Voor het headerplaatje kun je https://csrdelft.nl/plaetjes/courant/courant_header_20210208.jpg gebruiken. Kan je jouw versie van het beeldmerk ook daar neerzetten (of hiero, dan zet ik m daar neer)

2021-02-08 11:42 UTC, qurben reviewed
Nog even de locaties van de header plaetjes fixen en dan is ie goed 👍

2021-02-08 14:19 UTC, merged